config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :schedules
  resources :action_plans
  devise_for :users
  get 'dashboards', to: 'dashboards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'schedules#index'

  # resource :mypage
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :action_plan
  has_many :schedule_customers, dependent: :destroy
  has_many :customers, through: :schedule_customers
  accepts_nested_attributes_for :customers,
                                allow_destroy: true

  validates :target, numericality: { only_integer: true }, on: :update
  validates :achievement, numericality: true, on: :update
  validates :body, presence: true, length: { maximum: 512 }

  def self.term_between(term_from, term_to)
    where("term_from >= ? and term_to < ?", term_from, term_to)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    if params[:from] && params[:to]
      @schedules = Schedule.term_between(
        Date.new(params[:from][:year].to_i, params[:from][:month].to_i, params[:from][:day].to_i),
        Date.new(params[:to][:year].to_i, params[:to][:month].to_i, params[:to][:day].to_i).tomorrow)
    else
      @schedules = Schedule.all
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show; end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit; end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)
    respond_to do |format|
      @schedule.target ||= 0
      @schedule.achievement ||= 0
      if @schedule.save
        format.html { redirect_to @schedule,
          notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created,
          location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule,
          notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok,
          location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url,
        notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:term_from, :term_to, :target,
        :achievement, :body, :destination, :action_plan_id,
        :activity_setup, :activity_interview, :activity_inspection,
        :activity_presentation, :activity_engagement,
        { customer_ids: [] })
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :term_from %>
    <%= form.datetime_select :term_from, id: :schedule_term_from %>
  </div>

  <div class="field">
    <%= form.label :term_to %>
    <%= form.datetime_select :term_to, id: :schedule_term_to %>
  </div>

  <%# only # edit #%>
  <% if @schedule.persisted? %>
    <div class="field">
      <%= form.label :target %>
      <%= form.text_field :target, id: :schedule_target %>
    </div>

    <div class="field">
      <%= form.label :achievement %>
      <%= form.text_field :achievement, id: :schedule_achievement %>
    </div>
  <% end %>
  <%# # # # # # # #%>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :schedule_body %>
  </div>

  <div class="field">
    <%= form.label :destination %>
    <%= form.text_field :destination, id: :schedule_destination %>
  </div>

  <%# only # new #%>
  <% unless @schedule.persisted? %>
    <div class="field">
      <%= form.label :action_plan %>
      <%= form.collection_select :action_plan_id, ActionPlan.all, :id, :body, prompt: true %>
    </div>
  <% end %>
  <%# # # # # # # #%>

  <%# only # edit #%>
  <% if @schedule.persisted? %>
    <div class="field">
      <%= form.label :setup %>
      <%= form.check_box :activity_setup %>
    </div>

    <div class="field">
      <%= form.label :interview %>
      <%= form.check_box :activity_interview %>
    </div>

    <div class="field">
      <%= form.label :inspection %>
      <%= form.check_box :activity_inspection %>
    </div>

    <div class="field">
      <%= form.label :presentation %>
      <%= form.check_box :activity_presentation %>
    </div>

    <div class="field">
      <%= form.label :engagement %>
      <%= form.check_box :activity_engagement %>
    </div>
  <% end %>
  <%# # # # # # # #%>

  <div class="field">
    <%= form.label :customers %><br>
    <%= collection_check_boxes(:schedule, :customer_ids, Customer.all, :id, :first_name) do |customer|  %>
      <% customer.label { customer.check_box + customer.text } %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Schedules</h1>

<%= form_tag(schedules_path, method: 'get') do %>
  <div class="field">
    <%= select_date Date.today, prefix: :from, use_month_numbers: true,
      start_year: Date.today.year, end_year: Date.today.year + 12 %>
  </div>

  <div class="field">
    <%= select_date Date.today, prefix: :to, use_month_numbers: true, 
      start_year: Date.today.year, end_year: Date.today.year + 12 %>
  </div>

  <div class="actions">
    <%= submit_tag 'Search!' %>
  </div>
<% end %>

<%= form_tag(schedules_path, method: "get") do %>
  <div class="field">
    <%= text_field_tag :achievement, params[:achievement] %>
  </div>

  <div class="actions">
    <%= submit_tag 'Search!' %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Term from</th>
      <th>Term to</th>
      <th>Target</th>
      <th>Achievement</th>
      <th>Body</th>
      <th>Destination</th>
      <th>Action Plan</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.term_from %></td>
        <td><%= schedule.term_to %></td>
        <td>
          <% if schedule.target == 0 %>
            <%= '未設定' %>
          <% else %>
            <%= schedule.target %>
          <% end %>
        </td>
        <td>
          <% if schedule.achievement == 0 %>
            <%= '未設定' %>
          <% else %>
            <%= schedule.achievement %>
          <% end %>
        </td>
        <td><%= schedule.body %></td>
        <td><%= schedule.destination %></td>
        <td><%= schedule.action_plan.body %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Dashboards', dashboards_path(action_plan_id: schedule.action_plan_id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p>
  <strong>Term from:</strong>
  <%= @schedule.term_from %>
</p>

<p>
  <strong>Term to:</strong>
  <%= @schedule.term_to %>
</p>

<p>
  <strong>Target:</strong>
  <%= @schedule.target %>
</p>

<p>
  <strong>Achievement:</strong>
  <%= @schedule.achievement %>
</p>

<p>
  <strong>Body:</strong>
  <%= @schedule.body %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @schedule.destination %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>