config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :schedules
  resources :action_plans
  devise_for :users
  get 'dashboards', to: 'dashboards#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'schedules#index'

  # resource :mypage
end

app/models/action_plan.rb
class ActionPlan < ApplicationRecord
  belongs_to :user
  has_many :schedules, dependent: :nullify
  
  validates :target, presence: true,
            numericality: { only_integer: true }
  validates :achievement, presence: true,
            numericality: true
  validates :body, presence: true, length: { maximum: 64 }
end

app/controllers/action_plans_controller.rb
class ActionPlansController < ApplicationController
  before_action :set_action_plan, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /action_plans
  # GET /action_plans.json
  def index
    @action_plans = ActionPlan.all
  end

  # GET /action_plans/1
  # GET /action_plans/1.json
  def show; end

  # GET /action_plans/new
  def new
    @user = current_user
    @action_plan = ActionPlan.new
  end

  # GET /action_plans/1/edit
  def edit; end

  # POST /action_plans
  # POST /action_plans.json
  def create
    @action_plan = ActionPlan.new(action_plan_params)

    respond_to do |format|
      @action_plan.user_id = current_user.id
      if @action_plan.save
        format.html { redirect_to @action_plan,
          notice: 'Action plan was successfully created.' }
        format.json { render :show, status: :created,
          location: @action_plan }
      else
        format.html { render :new }
        format.json { render json: @action_plan.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /action_plans/1
  # PATCH/PUT /action_plans/1.json
  def update
    respond_to do |format|
      if @action_plan.update(action_plan_params)
        format.html { redirect_to @action_plan,
          notice: 'Action plan was successfully updated.' }
        format.json { render :show, status: :ok,
          location: @action_plan }
      else
        format.html { render :edit }
        format.json { render json: @action_plan.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /action_plans/1
  # DELETE /action_plans/1.json
  def destroy
    @action_plan.destroy
    respond_to do |format|
      format.html { redirect_to action_plans_url,
        notice: 'Action plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_action_plan
    @action_plan = ActionPlan.find(params[:id])
  end

  def action_plan_params
    params.require(:action_plan).permit(:term_from, :term_to,
      :target, :achievement, :body)
  end
end

app/helpers/action_plans_helper.rb
module ActionPlansHelper
end

app/views/action_plans/_form.html.erb
<%= form_with(model: action_plan, local: true) do |form| %>
  <% if action_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(action_plan.errors.count, "error") %> prohibited this action_plan from being saved:</h2>

      <ul>
      <% action_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :term_from %>
    <%= form.text_field :term_from, id: :action_plan_term_from %>
  </div>

  <div class="field">
    <%= form.label :term_to %>
    <%= form.text_field :term_to, id: :action_plan_term_to %>
  </div>

  <div class="field">
    <%= form.label :target %>
    <%= form.text_field :target, id: :action_plan_target %>
  </div>

  <div class="field">
    <%= form.label :achievement %>
    <%= form.text_field :achievement, id: :action_plan_achievement %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body, id: :action_plan_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/action_plans/edit.html.erb
<h1>Editing Action Plan</h1>

<%= render 'form', action_plan: @action_plan %>

<%= link_to 'Show', @action_plan %> |
<%= link_to 'Back', action_plans_path %>

app/views/action_plans/index.html.erb
<h1>Action Plans</h1>

<table>
  <thead>
    <tr>
      <th>Term from</th>
      <th>Term to</th>
      <th>Target</th>
      <th>Achievement</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @action_plans.each do |action_plan| %>
      <tr>
        <td><%= action_plan.term_from %></td>
        <td><%= action_plan.term_to %></td>
        <td><%= action_plan.target %></td>
        <td><%= action_plan.achievement %></td>
        <td><%= action_plan.body %></td>
        <td><%= link_to 'Show', action_plan %></td>
        <td><%= link_to 'Edit', edit_action_plan_path(action_plan) %></td>
        <td><%= link_to 'Destroy', action_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Dashboards', dashboards_path(action_plan_id: action_plan.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Action Plan', new_action_plan_path %>

app/views/action_plans/new.html.erb
<h1>New Action Plan</h1>

<%= render 'form', action_plan: @action_plan %>

<%= link_to 'Back', action_plans_path %>

app/views/action_plans/show.html.erb
<p>
  <strong>Term from:</strong>
  <%= @action_plan.term_from %>
</p>

<p>
  <strong>Term to:</strong>
  <%= @action_plan.term_to %>
</p>

<p>
  <strong>Target:</strong>
  <%= @action_plan.target %>
</p>

<p>
  <strong>Achievement:</strong>
  <%= @action_plan.achievement %>
</p>

<p>
  <strong>Body:</strong>
  <%= @action_plan.body %>
</p>

<%= link_to 'Edit', edit_action_plan_path(@action_plan) %> |
<%= link_to 'Back', action_plans_path %>